---
all:
  hosts:
  children:
    agents:
      hosts:
        iosbuild1.standardbank.co.za:
          ansible_host: 10.18.17.240
        iosbuild3.standardbank.co.za:
          ansible_host: 10.18.17.242
        iosbuild8.standardbank.co.za:
          ansible_host: 10.18.17.246
        iosbuild9.standardbank.co.za:
          ansible_host: 10.18.17.247
        iosbuild10.standardbank.co.za:
          ansible_host: 10.18.17.248
    local_vms:
      hosts:
        10.18.22.110:
    local:
      hosts:
        127.0.0.1:
          ansible_user: andrasfindt
