- hosts: bodhis
  gather_facts: true # https://github.com/zzet/ansible-rbenv-role/issues/37
  become: true
  vars:
    username: "{{ ansible_user_id }}"
    usergroup: "{{ ansible_user_gid }}"
    git_install_from_source: false
    git_install_path: /usr/local
    rbenv:
      env: user
      version: v0.4.0
      default_ruby: 2.6.5
      rubies:
        - version: 2.6.5
          env:
            RUBY_CONFIGURE_OPTS: "--enable-shared"
    rbenv_extra_depends:
    #      - libjemalloc1
    #      - libjemalloc-dev
    homebrew_installed_packages:
      - git
    homebrew_user: "{{ username }}"
    homebrew_group: "{{ usergroup }}"
  roles:
    - role: andrasfindt.brew-zsh
      become: no
#    - role: zzet.rbenv
#      become: no
#      rbenv_users:
#        - "{{ username }}"
#      default_gems_file: gems
#      rbenv_set_vars: true