- hosts: bodhis
  gather_facts: true # https://github.com/zzet/ansible-rbenv-role/issues/37
  become: true
  vars:
    git_install_from_source: false
    git_install_path: /usr/local
    rbenv:
      env: user
      version: v0.4.0
      default_ruby: 2.6.5
      rubies:
        - version: 2.6.5
          env:
            RUBY_CONFIGURE_OPTS: "--enable-shared --with-jemalloc"
    rbenv_extra_depends:
      - libjemalloc1
      - libjemalloc-dev

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: geerlingguy.git
    - role: zzet.rbenv
      rbenv_users:
        - slave