---
- hosts: local_vms
  gather_facts: true # https://github.com/zzet/ansible-rbenv-role/issues/37
  become: true
  vars:
    username: build
    usergroup: staff
    git_install_from_source: false
    git_install_path: /usr/local
    homebrew_installed_packages:
      - git
    homebrew_user: "{{ username }}"
    homebrew_group: "{{ usergroup }}"
    powerlevel10k_use_default_config: true
  roles:
    - role: andrasfindt.brew-zsh
      become: no
