---
- name: install build depends
  dnf:
    name: "{{ rbenv_dnf_packages }}"
    state: present
  become: true

- name: install build depends
  dnf:
    name: "{{ rbenv_extra_depends }}"
    state: present
  become: true
